language: csharp
sudo: required
dist: trusty
mono: none
env:  
  - CLI_VERSION=latest
os:
  - linux
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
    - master
git:
  depth: 3

install:
    - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
    - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview2.1/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
    - export PATH="$DOTNET_INSTALL_DIR:$PATH"

script:
  - sh ./Build.sh
