language: csharp
sudo: required
dist: trusty
os:
  - linux
mono:
  - 4.2.3
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
branches:
  only:
    - master

script:
  - ./build.sh
