language: csharp
env:
  - CLI_VERSION=LATEST
git:
    depth: 2
dist: trusty
addons: 
    apt:
        sources:
          - debian-sid
        packages:
          - gettext
          - libcurl4-openssl-dev
          - libicu-dev
          - libssl-dev
          - libunwind8
          - zlib1g

branshes:
    only:
      - master

before install:
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  

script: 
    - sh ./Build.sh
