image: visual studio 2015
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
install:
  - ps: ri global.json
  - ps: rni global_ci.json global.json

build_script:
  - Build_104LTS.cmd

clone_depth: 1
test: off
deploy: off
