init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
environment:
  matrix:
    - CLI_VERSION: Latest
    
install:
  - ps: $url = "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.1/scripts/obtain/dotnet-install.ps1"
build_script:
  - Build.cmd
clone_depth: 1
test: off
deploy: off
