init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
environment:
  matrix:
    - CLI_VERSION: 1.0.0-preview2.1
    
install:
  - ps: $url = "https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/$($env:CLI_VERSION)/dotnet-dev-win-x64.$($env:CLI_VERSION.ToLower()).zip"
build_script:
  - Build.cmd
clone_depth: 3
test: off
deploy: off
