init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
environment:
  matrix:
    - CLI_VERSION: Latest
    
install:
  - ps: .{Invoke-WebRequest -useb https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0-preview4/scripts/obtain/dotnet-install.ps1} | Invoke-Expression; dotnet-install
build_script:
  - Build.cmd
clone_depth: 3
test: off
deploy: off
