image: visual studio 2015
init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    
install:
  - ps: ri global.json
  - ps: rni global_appveyor.json global.json
build_script:
  - Build.cmd
clone_depth: 1
test: off
deploy: off
